main/src/JAG.DevTest2019.WebHost/Models/LeadViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JAG.DevTest2019.Host.Models
{
    public class LeadViewModel
    {
        public LeadViewModel()
        {
            Results = new LeadResultViewModel();
        }

        public string TrackingCode { get; }

        [Display(Name = "Select your gender?")]
        public string Gender { get; set; }

        [Display(Name = "Select your language?")]
        public string Language { get; set; }

        [Display(Name = "Select your blood type?")]
        public string BloodType { get; set; }

        [Required(ErrorMessage = "First Name is required")]
        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "Last Name is required")]
        [Display(Name = "Surname")]
        public string Surname { get; set; }

        [Required]
        [EmailAddress]
        [Display(Name = "Email Address")]
        public string EmailAddress { get; set; }

        [Required]
        [RegularExpression(@"^(\d{10})$", ErrorMessage = "Contact Number should be a valid telephone number")]
        [Display(Name = "Contact Number")]
        public virtual string ContactNumber { get; set; }

        public List<SelectListItem> Genders { get; } = new List<SelectListItem>()
        {
            new SelectListItem()  {Text="Male", Value = "Male"},
            new SelectListItem()  {Text="Female", Value = "Female"},
        };

        public List<SelectListItem> Languages { get; } = new List<SelectListItem>()
        {
            new SelectListItem()  {Text="English", Value = "English"},
            new SelectListItem()  {Text="Afrikaans", Value = "Afrikaans"},
            new SelectListItem()  {Text="Zulu", Value = "Zulu"},
            new SelectListItem()  {Text="Xhosa", Value = "Xhosa"},
            new SelectListItem()  {Text="Sesotho ", Value = "Sesotho"},
        };

        public List<SelectListItem> BloodTypes { get; } = new List<SelectListItem>()
        {
            new SelectListItem()  {Text="O+", Value = "O+"},
            new SelectListItem()  {Text="O-", Value = "O-"},
            new SelectListItem()  {Text="A+", Value = "A+"},
            new SelectListItem()  {Text="A-", Value = "A-"},
            new SelectListItem()  {Text="B+", Value = "B+"},
            new SelectListItem()  {Text="B-", Value = "B-"},
            new SelectListItem()  {Text="AB+", Value = "AB+"},
            new SelectListItem()  {Text="AB-", Value = "AB-"},
        };

        public LeadResultViewModel Results { get; set; }
    }
}

main/src/JAG.DevTest2019.WebHost/Controllers/LeadController.cs
using JAG.DevTest2019.Host.Models;
using System;
using System.Net.Http;
using System.Web.Mvc;
using JAG.DevTest2019.Model;
using System.Web.Http;
using Newtonsoft.Json;

namespace JAG.DevTest2019.Host.Controllers
{
    public class LeadController : Controller
    {
        LeadsRepository leadRepo = new LeadsRepository();
        public ActionResult Index()
        {
            return View(new LeadViewModel());
        }

        [System.Web.Http.HttpPost]
        public ActionResult SubmitLead(LeadViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            //6. Call the WebAPI service here & pass results to UI
            var LeadId = new Random().Next();
            var lead = new Lead()
            {
                ClientIpAddress = "127.0.0.1",
                ContactNumber = model.ContactNumber,
                EmailAddress = model.EmailAddress,
                FirstName = model.FirstName,
                LeadId = LeadId,
                LeadParameters = null,
                ReferrerUrl = "www.jagmethod.com",
                Surname = model.Surname,
                TrackingCode = Guid.NewGuid().ToString("n").Substring(0, 20),
                UserAgent = "James Bond"
            };

            LeadService.Controllers.LeadController controller = new LeadService.Controllers.LeadController()
            {
                Request = new HttpRequestMessage(),
                Configuration = new HttpConfiguration()
            };
            var response = controller.Post(lead);
            var responseContent = response.Content.ReadAsStringAsync().Result;
            var leadResponse = JsonConvert.DeserializeObject<LeadResponse>(responseContent);

            LeadViewModel result = new LeadViewModel()
            {
                Results = new LeadResultViewModel()
                {
                    LeadId = leadResponse.LeadId,
                    IsSuccessful = leadResponse.IsSuccessful,
                    Message = string.Join("", leadResponse.Messages)
                }

            };

            return Json(result.Results);
        }


        [System.Web.Http.HttpGet]
        public ActionResult GetLeadStatus()
        {
            return Json(leadRepo.GetLeadStatus(), JsonRequestBehavior.AllowGet);
        }

        [System.Web.Http.HttpPost]
        public ActionResult RecordNewLeadId(int? id)
        {
            LeadService.Controllers.LeadController controller = new LeadService.Controllers.LeadController()
            {
                Request = new HttpRequestMessage(),
                Configuration = new HttpConfiguration()
            };

            controller.PollDB(id);
           
            return Json(new {LeadId = id });
        }

        [System.Web.Http.HttpGet]
        public ActionResult GetLeads()
        {
            return Json(leadRepo.GetData(), JsonRequestBehavior.AllowGet);
        }
    }
}

main/src/JAG.DevTest2019.WebHost/Views/Lead/Index.cshtml
@{
    Layout = "~/Views/shared/_LeadLayout.cshtml";
    ViewBag.Title = "Page title";
}
@using JAG.DevTest2019.Host.Models
@model LeadViewModel

@section Meta{
    <meta name="description" content="Default site" />
    <meta name="keywords" content="Default" />
}

<section id="quote" class="main-banner" style="background-image: url(/Content/Images/Banners/car-insurance.jpg)">
    <div class="slant-left col-md-9 pull-left">
        <div class="col-md-8 col-md-offset-2">
            <div id="form-add-lead" class="capture-form">
                <h1 class="text-center">Insurance</h1>
                <h4>Don’t pay too much, find the best insurance quotes and start saving today!</h4>

                @using (Html.BeginForm(null, null, FormMethod.Post, new { id = "addLeadForm" }))
                {
                    @Html.AntiForgeryToken();
                    <div class="col-md-12">
                        <p>
                            <input type="hidden" value="@Model.TrackingCode" id="hdnTrackingCode" />

                            My name is
                            @Html.TextBoxFor(model => model.FirstName, new { @placeholder = Html.DisplayNameFor(model => model.FirstName) })
                            @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "input-validation-color" })
                            @Html.TextBoxFor(model => model.Surname, new { @placeholder = Html.DisplayNameFor(model => model.Surname) })
                            @Html.ValidationMessageFor(model => model.Surname, "", new { @class = "input-validation-color" })
                            You can contact me at
                            @Html.TextBoxFor(model => model.EmailAddress, new { @placeholder = Html.DisplayNameFor(model => model.EmailAddress) })
                            @Html.ValidationMessageFor(model => model.EmailAddress, "", new { @class = "input-validation-color" }) or
                            @Html.TextBoxFor(model => model.ContactNumber, new { @placeholder = Html.DisplayNameFor(model => model.ContactNumber) })
                            @Html.ValidationMessageFor(model => model.ContactNumber, "", new { @class = "input-validation-color" })
                            to help me save on insurance
                            I am @Html.DropDownListFor(model => model.Gender, Model.Genders, "Gender") and my language preference is
                            @Html.DropDownListFor(model => model.Language, Model.Languages, "Language")
                            and my blood type is @Html.DropDownListFor(model => model.Language, Model.BloodTypes, "BloodType")
                        </p>
                    </div>
                    <div class="clearfix"></div>

                    <div class="col-md-12 text-center">
                        <button type="submit" id="btnSubmit" class="orange-button">Get Quotes Now</button>
                    </div>
                    <div id="loader" hidden class="col-md-12 text-center">
                        <div>
                            <img src="~/Content/Images/Loader/ajax-loader.gif" />
                        </div>
                    </div>
                }
                <div id="successMessage" class="col-md-12 text-center" hidden>
                    <img src="~/Content/Images/Products/new-success.png" height="24px" />
                    <span id="resMessge"></span>
                </div>

                <div class="clearfix"></div>
            </div>

        </div>

    </div>
    <div class="clearfix"></div>
</section>
<div class="clearfix"></div>
<div class="container benefits-padding text-center">
    <h2>Benefits</h2>
    <div class="benefits-cols">
        <div class="col-md-3 text-center text-instructions">
            <img src="~/Content/Images/Products/new-save.png" />
            <p>People saved on insurance</p>
        </div>
        <div class="col-md-3 text-center text-instructions">
            <img src="~/Content/Images/Products/new-calling.png" />
            <p>99.99% were called in under 5 minutes</p>
        </div>
        <div class="col-md-3 text-center text-instructions">
            <img src="~/Content/Images/Products/new-success.png" />
            <p>96% believe these stats</p>
        </div>
        <div class="col-md-3 text-center text-instructions">
            <img src="~/Content/Images/Products/new-clients.png" />
            <p id="queriesServiceNumber">Over 6000000 queries serviced</p>
        </div>
        <div class="clearfix"></div>
    </div>
</div>
<div id="quote" class="testimonial-banner" style="background-image: url('../../Content/Images/Banners/best-car-insurance.jpg');">
    <div class="slant-right col-md-9 pull-right">
        <div class="col-md-6 col-md-offset-3 testimonials text-center">
            <b>Getting the lowest insurance quote has never been so easy:</b>
            <p>
                <b>Joe Blogs (26 years)</b><br /><br />
                Telsa model x <br />
                Was paying R999,999.99<br />
                Now paying R99.99
            </p>
            <h2 class="highlight">Insurance saving of {lots of %}</h2>
        </div>
        <div class="clearfix"></div>
    </div>
    <div class="clearfix"></div>
</div>
<div class="clearfix"></div>
<div class="container-blue">
    <div class="col-md-6 col-md-offset-3 text-center">
        <h1>Get a quote and</h1>
        <h1 class="green">start saving now</h1>
        <p>Get in touch to receive insurance quotes from South Africa’s top insurance companies. Getting the lowest insurance premiums has never been so easy.</p>
        <a id="lnkGetQuote" href="#quote" class="orange-button">Get a quote now</a>
    </div>
    <div class="clearfix"></div>
</div>

@section Scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            $('#lnkLead').addClass('activeMenu');
        })

    </script>

    <script type="text/javascript">

        $(function() {
            $("#addLeadForm").submit(function (event) {
                event.preventDefault();

                var form = $("#addLeadForm");
                form.validate();
                if (form.valid()) {
                    $("#btnSubmit").prop("disabled", true);
                    $('#btnSubmit').css('cursor', 'not-allowed');
                    $("#loader").prop("hidden", false);

                    var formData = $('#addLeadForm').serializeObject();
                    var data = JSON.stringify(formData);

                    $.ajax({
                        type: "POST",
                        contentType: "application/json; charset=utf-8",
                        url: '@Url.Action("SubmitLead", "Lead")',
                        data: data,
                        datatype: "json",
                        success: function(response) {
                            $("#btnSubmit").prop("disabled", false);
                            $('#btnSubmit').css('cursor', 'pointer');
                            $("#loader").prop("hidden", true);
                            $("#addLeadForm")[0].reset();
                            $("#successMessage").prop("hidden", false);
                            $("#resMessge").text(response.Message);
                            $("#resMessge").html(response.Message);
                        },
                        error: function(response) {
                        },

                    });
                } else {
                    $("#successMessage").prop("hidden", true);
                }
            });
        });

        $.fn.serializeObject = function() {
            var o = {};
            var a = this.serializeArray();
            $.each(a,
                function() {
                    if (o[this.name] !== undefined) {
                        if (!o[this.name].push) {
                            o[this.name] = [o[this.name]];
                        }
                        o[this.name].push(this.value || '');
                    } else {
                        o[this.name] = this.value || '';
                    }
                });
            return o;
        };
    </script>

    <script type="text/javascript">
        function randomly_increment_queries_serviced() {
            var n = localStorage.getItem('on_load_queries_serviced');
            if (n === null) {
                n = 6000000;
            }
            n++;
            var randomNum = Math.floor(Math.random() * 100);
            n = n + randomNum;
            localStorage.setItem("on_load_queries_serviced", n);
            document.getElementById('queriesServiceNumber').innerHTML = "Over " + n + " queries serviced";
        }

        setInterval('randomly_increment_queries_serviced()', 4000);

        function reset_counter() {
            localStorage.removeItem('on_load_queries_serviced');
        }

        window.onload = randomly_increment_queries_serviced;
    </script>

    <script type="text/javascript">

        function polling_database_for_changes() {
            var id = localStorage.getItem('last_inserted_id');
            if (id === null) {
                id = 0;
            }
            var interval = 60; // 60 seconds
            interval = interval * 1000;
            var obj = {};
            window.setInterval(poll, interval);
            function poll() {
                $.ajax({
                    url: "/Lead/GetLeadStatus",
                    type: "GET",
                    data: obj,
                    dataType: "json",
                    traditional: true,
                    contentType: "application/json; charset=utf-8",
                    success: function (lastInsertedId) {
                        if (parseInt(id) !== parseInt(lastInsertedId)) {
                            localStorage.setItem("last_inserted_id", lastInsertedId);
                            id = lastInsertedId;
                            new_records_to_console_window(lastInsertedId);
                        }
                    },
                    error: function (data) {
                        alert("An error has occured!!!");
                    }
                });
            }
        }
        setInterval('polling_database_for_changes()', 60000);

        window.onload = polling_database_for_changes;
    </script>

    <script type="text/javascript">
        function new_records_to_console_window(id) {
                $.ajax({
                    url: "/Lead/RecordNewLeadId",
                    type: "POST",
                    data: JSON.stringify({ id: id }),
                    dataType: "json",
                    traditional: true,
                    contentType: "application/json; charset=utf-8",
                    success: function (id) {
                    },
                    error: function (data) {
                        alert("An error has occured!!!");
                    }
                });
        }
    </script>
}